### ISSUE TITLE
Criar RestController para visualização de um cliente em cliente service

### ISSUE THREAD

**Issue by ThiagoInnwinkl** [ThiagoInnwinkl/helpr#1]
- [ ] Criar Controlador Rest
- [ ] Criar Serviço de Cliente
- [ ] Criar métodos para Endpoint de RestController
- [ ] Vincular os repositórios de cliente
- [ ] Testar Endpoint no Postman

**Comment by soulcode-acad** [comment]
Thiago deu show meus parabéns apanhou um pouco na gestão do Git mas o importante fez entregou o trem funcionando uma ou outra classe com erro de chamada e um pouco de sujeira de código. Porém de resto tudo passou nos testes base!
![image](https://user-images.githubusercontent.com/100297907/172920423-c747c415-8f0e-4520-8947-eb16351fcd00.png)
